### ISSUE TITLE
Fails on strange filenames

### ISSUE THREAD

**Issue by jayvdb** [rosylilly/git-set-mtime#8]
I get an error on https://gitlab.com/ciptamedia/ciptamedia-dev.gitlab.io/blob/a79291ff5/_posts/2013-03-09-Launching-Antologi-%E2%80%9CAmarah%E2%80%9D.markdown , on Linux

```
  /home/jayvdb/.rbenv/versions/2.4.3/lib/ruby/2.4.0/time.rb:254:in `make_time'
  /home/jayvdb/.rbenv/versions/2.4.3/lib/ruby/2.4.0/time.rb:370:in `parse'
  /home/jayvdb/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/git-set-mtime-485263aba2b6/lib/git/set/mtime.rb:19:in `block in apply'
  /home/jayvdb/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/git-set-mtime-485263aba2b6/lib/git/set/mtime.rb:13:in `each_line'
  /home/jayvdb/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/git-set-mtime-485263aba2b6/lib/git/set/mtime.rb:13:in `apply'
  /home/jayvdb/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /home/jayvdb/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /home/jayvdb/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /home/jayvdb/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /home/jayvdb/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/git-set-mtime-485263aba2b6/bin/git-set-mtime:4:in `<top (required)>'
  /home/jayvdb/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bin/git-set-mtime:23:in `load'
  /home/jayvdb/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bin/git-set-mtime:23:in `<top (required)>'
```

the filename is `_posts/2013-03-09-Launching-Antologi-\342\200\234Amarah\342\200\235.markdown`

**Comment by jayvdb** [comment]
`_uploads/Capture\ d’écran\ 2017-03-27\ à\ 15.09.55.png` also breaks
